### ISSUE TITLE
Header Parameters

### ISSUE THREAD

**Issue by anitha-sathish** [moon0326/swagger-ui-watcher#11]
Is Header parameter definition supported? 

When I try to add a header parameter, I see the below error:
Schema error at paths[<<Path Value>>].get.parameters[0]
should NOT have additional properties
additionalProperty: schema, in, name

Schema error at paths[<<Path Value>>].get.parameters[0].in
should be equal to one of the allowed values
allowedValues: body, formData, query, path

Please suggest on how the header parameters can be included.

**Comment by moon0326** [comment]
@anitha-sathish Could you post your definition? It only supports Swagger version 2. You might be trying to add a header parameter from version 3.

**Comment by anitha-sathish** [comment]
Thank you for your response.
Now, Iam able to define the header parameter in the yaml. But when I try to reference the header from .json using $ref, it is not being supported.

Is there any limitation in using $ref for Header parameters? Any suggestions on this please.

**Comment by moon0326** [comment]
@anitha-sathish it would be helpful if you can post your definitions.

As long as it is supported by version 2, I think it should be okay. This package is using https://github.com/BigstickCarpet/swagger-parser to validate Swagger syntax.

**Comment by anitha-sathish** [comment]
`PFA the defintions.
[Sample.zip](https://github.com/moon0326/swagger-ui-watcher/files/1780693/Sample.zip)

`

**Comment by anitha-sathish** [comment]
Any suggestions please?

**Comment by moon0326** [comment]
@anitha-sathish I think you are using Swagger 3 syntax. I don't see ```schema``` property from Swagger 2 documentation (https://swagger.io/docs/specification/2-0/describing-parameters/). 

The error is

```
Schema error at paths['/customer/appointment/details'].get.parameters[0]
should NOT have additional properties
additionalProperty: schema, name, in
```

**Comment by moon0326** [comment]
I am going to experiment with Swagger 3 over the weekend. If you are not hurry, try with Swagger 2 syntax and check back next week.

**Comment by moon0326** [comment]
@anitha-sathish Just published version 2 to support OpenAPI 3. Please try the latest version. 

```
npm install swagger-ui-watcher@2.0.0 -g
```

**Comment by moon0326** [comment]
Closing it as there is no response.
