### ISSUE TITLE
Example illustrating use of external references / multiple files

### ISSUE THREAD

**Issue by woutgg** [moon0326/swagger-ui-watcher#16]
I tried splitting the spec I'm writing into multiple files but I keep getting this error (seemingly coming from swagger-editor-dist):

    Could not resolve reference because of: Tried to resolve a relative URL, without having a basePath. path: 'referenced-file.yml' basePath: 'undefined'

I've tried variations on the path but can't seem to get it right, nor could I find information on how to do this, or how to specify a `basePath` anywhere. The error is always the same.

Since the readme explicitly mentions external references are supported, I'd very much like an example on how to get this done. I'd be really grateful. :)

**Comment by woutgg** [comment]
Ok I got it working now, and probably earlier as well. The problem is I did not notice, because of two reasons:

1. Somehow the error is not removed from the list after an auto-reload; after another manual reload it does disappear.
2. The ui-watcher approach is to resolve all references before passing the spec to swagger-editor (correct?). If somehow the resolution of a ref fails, it produces this misleading error while the actual problem is an incorrect path or something else json-refs could not handle. Perhaps it would be more informative to display those separately.

   A quick-and-dirty hack to collect and log any json-refs problems (replacing [this line](https://github.com/moon0326/swagger-ui-watcher/blob/master/index.js#L29))

       var resErrors = {};
       for (const [k,v] of Object.entries(results.refs)) {
         if ('missing' in v && v.missing === true)
           resErrors[k] = v.error;
       }
       console.log(resErrors);
       return results.resolved;

Improving these two issues would make it easier to spot and resolve mistakes in reference paths.

**Comment by moon0326** [comment]
@woutgg Thank you. I will take a look. Did you get a chance to look at the comment I left in your PR? Thanks.

**Comment by moon0326** [comment]
@woutgg would it be possible for you to give me an example? I'm trying to work on it, but it would be nice to have an example that I can replicate. Thanks!

**Comment by woutgg** [comment]
Of course!

Try this as `openapi.yml`:
```yaml
openapi: "3.0.1"
info:
  title: json-refs test API
  version: v1
paths:
  /resource1:
    $ref: 'resource1.yml'
  /missing-resource:
    $ref: 'missing-resource.yml'
```

And this as `resource1.yml` (note the mis-indented line `responses:`):
```yaml
get:
      responses:
    200:
      description: Dummy response
```

This will cause two errors:
```json
{
  "#/paths/~1resource1": "bad indentation of a mapping entry at line 3, column 5:\n        200:\n        ^: resource1.yml",
  "#/paths/~1missing-resource": "JSON Pointer points to missing location: missing-resource.yml"
}
```

I have already created a very crude way to get these errors in the web view (by having `bundle()` return an object like `{'bundle': ..., 'json_resolution_errors': [...] }`) but it will take a bit of thinking as to how/where these errors should be displayed in a clean fashion.

Let me know if you want more input.

**Comment by moon0326** [comment]
@woutgg thank you for the example. My apologies for the delay. It's been busy this week. I will look into it this weekend. I'm gonna try to apply what you have recommended in your original post.

**Comment by moon0326** [comment]
@woutgg Created a PR https://github.com/moon0326/swagger-ui-watcher/pull/17 

I used your code snippet above. It works for me. If it looks good, I will merge and release a new version. Thank you for your code snippet.

**Comment by woutgg** [comment]
Looks good, although I thought the errors would be somewhat easier to read with the newlines being output properly. I've added a commit which does that to [your branch in my fork](https://github.com/woutgg/swagger-ui-watcher/tree/feature/display-errors-from-each-ref).

**Comment by moon0326** [comment]
@woutgg If you can make PR, I will close mine and merge yours. Thank you for the change.

**Comment by woutgg** [comment]
@moon0326 Done, see #18.
