### ISSUE TITLE
Blank White screen on valid yml/json

### ISSUE THREAD

**Issue by cavnit** [moon0326/swagger-ui-watcher#20]
It seems that swagger-editor-dist 3.6.1 breaks swagger-ui-watcher, in that it displays a blank screen, even though everything is valid and all the html is there.

Using swagger-editor-dist 3.6.0 and it works again

**Comment by crudo** [comment]
Same here. Fixing the `swagger-editor-dist` to `3.6.0` is only workaround at this time.

**Comment by moon0326** [comment]
hi @cavnit and @crudo I will check on it tonight. 

thank you for the workaround @crudo

**Comment by moon0326** [comment]
@cavnit @crudo published 2.1.1, which uses 3.6.0 as a workaround for now.
