### ISSUE TITLE
Can't generate bundle from YAML

### ISSUE THREAD

**Issue by vpmv** [moon0326/swagger-ui-watcher#23]
Version 2.1.1 and up can't generate JSON bundles anymore using either -b or --bundle. 
v2.1.0 is unaffected.

**Comment by moon0326** [comment]
The problem has been fixed with version 2.1.4. Please take a look at PR https://github.com/moon0326/swagger-ui-watcher/pull/26

I tested creating a bundle locally and it worked fine for me. I'm gonna leave it for the next 1~2 days just in case.

**Comment by vpmv** [comment]
It's fixed for me. Thanks again!
