### ISSUE TITLE
$ref in paths doesnt work when more than 1 path is defined

### ISSUE THREAD

**Issue by Eksapsy** [moon0326/swagger-ui-watcher#28]
# I want to submit a
- [ ] Feature
- [x] Bug

# Expected Result
```json
// bundled.json
{
    "/server/settings/{server_id}": {
      "parameters": [
        {
          "name": "server_id",
          "in": "path",
          "required": true,
          "description": "The server's id",
          "schema": {
            "type": "string"
          }
        }
      ],
   },
   "/server/settings/{server_id}/name": {
      "parameters": [
        {
          "name": "server_id",
          "in": "path",
          "required": true,
          "description": "The server's id",
          "schema": {
            "type": "string"
          }
        }
      ]
   }
}
```

# What I got instead
```json
// bundled.json
{
    "/server/settings/{server_id}": {
      "parameters": [
        {
          "name": "server_id",
          "in": "path",
          "required": true,
          "description": "The server's id",
          "schema": {
            "type": "string"
          }
        }
      ]
   },
   "/server/settings/{server_id}/name": {
      "parameters": [
        {
          "$ref": "./components/parameters/ServerId.yaml#/ServerId"
        }
      ],
   }
}
```

The strangest thing is that **if I have only one of them** it works nice. 
It is like, you cant import two times the same component.

# Problem Prediction
**Probably** the problem is that the same parameter is imported two times, so the swagger compiler refuses to reimport the same module/parameter/component?

# edit 1
I tried to debug the source code of `swagger-ui-watcher`. It seems like it's a `json-ref` along with `js-yaml` issue.

Even though the `results.refs` seems to be right, the `results.resolved` seem to be bugged for some reason that I cant find why for the moment being.
I'll make a further research about it.

**Comment by moon0326** [comment]
Hi,

Thank you for the report. I will take a look and get back to you asap.

**Comment by moon0326** [comment]
Closing it as you opened a new ticket for whatever reason.
