### ISSUE TITLE
json-refs is a very buggy library - DO NOT use swagger-ui-watcher

### ISSUE THREAD

**Issue by Eksapsy** [moon0326/swagger-ui-watcher#29]
The title is not a "flame" issue, its more like `I dont want you to lose all your patience while you're trying to debug this library`.

Ive been trying for 2 days to fix my bugs with this `json-refs` and `js-yaml` library that you use explicitly in the Project.

There's always a problem with the relative path. Always. As I demonstrated in my previous issue, but in a much less descriptive manner. Now I will try to be as informative for the sake of keeping people out of frustration.

# Disclaimer & Why you should not use this library: 
- **I appreciate the work of the developers and my intentions are good**
- This issue is directed to the new users of this library more than it is directed to the devs
- This library is not remotely stable. It has **trivial** issues
- You should not use this library if you intent to use `$ref` known as references to other files. If you intent to use this library, keep it simple and try not to make it use the buggy **JSON-REFS** library that it uses internally. So **keep all of your OpenAPI stuff in *ONE FILE***

# I will demonstrate you an example.
## Directory Tree
```
├── api
│   ├── components
│   │   ├── parameters
│   │   │   ├── GuildId.yaml
│   │   │   └── ServerId.yaml
│   │   └── schemas
│   │       ├── ServerSettings.yaml
│   │       └── Server.yaml
│   ├── index.yaml
│   └── server
│       └── settings
│           └── serverId
│               ├── index.yaml
│               └── name
│                   └── index.yaml
├── index.js
└── package.json
```
## My Bundle compilation script
The `index.js` code in the root is almost identical to yours, except that it writes a bundle with all the results so I can debug it.
**./index.js**
[**hastebin url**](https://hastebin.com/vapawasowi.js)

## The different YAML configurations and their errors
**./api/index.yaml**
[**api/index.yaml**](https://hastebin.com/hanuyexiyu.yaml)

*The rest dont matter for the time being. The first json-refs bug has only to do with `./api/index.yaml` only.

When I run the `index.js` script with this specific `api/index.yaml` file, the errors are of type `missing location`. 
### Error with relative paths to the YAML files
```json
{ '#/paths/~1server~1settings~1{server_id}':
   'JSON Pointer points to missing location: ./server/settings/serverId/index.yaml#/path',
  '#/paths/~1name':
   'JSON Pointer points to missing location: ./server/settings/serverId/name/index.yaml#/path',
  '#/components/parameters/ServerId':
   'JSON Pointer points to missing location: ./components/parameters/ServerId.yaml#/ServerId',
  '#/components/parameters/GuildId':
   'JSON Pointer points to missing location: ./components/parameters/ServerId.yaml#/ServerId',
  '#/components/schemas/Server':
   'JSON Pointer points to missing location: ./components/schemas/Server.yaml#/Server',
  '#/components/schemas/ServerSettings':
   'JSON Pointer points to missing location: ./components/schemas/ServerSettings.yaml#/ServerSettings' }
```

What? The paths were supposed to be relative to the file itself, not to the script.
But okay, no big deal right? 
_Ill just change the paths to be the relative paths to our `./index.js` script then._

*New* **./api/index.yaml**
[**api/index.yaml**](https://hastebin.com/efihopuriw.yaml)

### Error with relative paths to the JS script
```json
{ '#/paths/~1server~1settings~1{server_id}/parameters/0':
   'JSON Pointer points to missing location: ./api/components/parameters/ServerId.yaml#/ServerId',
  '#/paths/~1name/parameters/0':
   'JSON Pointer points to missing location: ./api/components/parameters/ServerId.yaml#/ServerId' }
```

**./api/server/settings/serverId/index.yaml**
```yaml
path:
  parameters:
    - $ref: '../../../index.yaml#/components/parameters/ServerId'
```
**./api/server/settings/serverId/name/index.yaml**
```yaml
path:
  parameters:
    - $ref: '../../../../index.yaml#/components/parameters/ServerId'
```

What? Now the problem is that the paths are not relative to the YAML files? Really?

Anyways.
My point is that **Swagger-UI-Watcher** is very buggy and you should not use that for professional use or even amatuer if you intent to have references to other files.
You're gonna lose all of your patience trying to debug it, because it uses **JSON-REFS** which is a library that barely has 200 stars and is barely maintained.
**JSON-REFS** seems to have many bugs.

So, unless someone makes a good **JSON-REFS** library or fixes all of the trivial bugs of **JSON-REFS**, dont attempt using this without realizing what you're going to do.

**Comment by moon0326** [comment]
Thank you, but please upload your example files so I can at least test them myself. It is always better to let othets test exactly what you are testing.

**Comment by moon0326** [comment]
Closing. Reopen if you are willing to upload your example files.

**Comment by Eksapsy** [comment]
Good morning from my place @moon0326 !
No I actually gave the other ones as well. Not only the `/api/index.yaml`. I just didnt give the other ones in links because they were small enough.

**./api/server/settings/serverId/index.yaml**
```yaml
path:
  parameters:
    - $ref: '../../../index.yaml#/components/parameters/ServerId'
```

**./api/server/settings/serverId/name/index.yaml**
```yaml
path:
  parameters:
    - $ref: '../../../../index.yaml#/components/parameters/ServerId'```

**Comment by Eksapsy** [comment]
Good morning from my place @moon0326 !
No I actually gave the other ones as well. Not only the `/api/index.yaml`. I just didnt give the other ones in links because they were small enough.

*(copy-pasted from original-post)*
**./api/server/settings/serverId/index.yaml**
```yaml
path:
  parameters:
    - $ref: '../../../index.yaml#/components/parameters/ServerId'
```

**./api/server/settings/serverId/name/index.yaml**
```yaml
path:
  parameters:
    - $ref: '../../../../index.yaml#/components/parameters/ServerId'
```

And I think everything you need to know is actually described as much as possible. If something is not described well enough, it's probably because I dont have enough information about it already. But Im pretty sure that everything you need to know is described here.

**Comment by moon0326** [comment]
Again, please upload the files, not just a one file. I'm pretty sure there is a problem, but I mean...I need reproducible files. Why don't you just create a repository with all your files? I will just clone.

**Comment by Eksapsy** [comment]
I have your back.
https://github.com/Eksapsy/swagger-ui-29

Gotcha. If you have any questions tell me. Happy to help.

**Comment by moon0326** [comment]
Thank you! I will try to reproduce it locally.

**Comment by moon0326** [comment]
Ok, I've looked at your files.

You have two issues with your files.

1. Missing version and info. Your index file is not a valid OpenAPI file.
2. Your paths are also invalid. They are missing operations.

Lastly, I think there is a confusion. Your index file has "./api/server...." for the references. Those have to be relative to your index file. You just need to remove "./api" then they will be included.

I was able to use your file with the following modifications.

Updated index.yaml

```
openapi: "3.0.0"
info:
    version: 1.0.0
    title: Test
paths:
  /server/settings/{server_id}:
    $ref: './server/settings/serverId/index.yaml#/path'
  /name:
    $ref: './server/settings/serverId/name/index.yaml#/path'
components:
  parameters:
    ServerId:
      $ref: './components/parameters/ServerId.yaml#/ServerId'

```

Updated server/settings/serverId/index.yaml

```
path:
  get:
    summary: test
    responses:
      "200":
        description: test
    parameters:
      - $ref: '../../../index.yaml#/components/parameters/ServerId'
```

I'm pretty sure both json-ref and this little script are not perfect, but they work just fine for most use cases. I'm not sure where your problems are.

**Comment by Eksapsy** [comment]
```
You have two issues with your files.

1. Missing version and info. Your index file is not a valid OpenAPI file.
2. Your paths are also invalid. They are missing operations.
```
1. Yes, that's because I was testing the `json-refs` dependency. Defining the `openapi version and info` would be useless in that case.
2. Read my original post. I tested both. And I got on both errors.
And with your updated files I get these errors
```bash
$ yarn start
yarn run v1.9.4
$ node ./index.js
{ '#/paths/~1server~1settings~1{server_id}':
   'JSON Pointer points to missing location: ./server/settings/serverId/index.yaml#/path',
  '#/paths/~1name':
   'JSON Pointer points to missing location: ./server/settings/serverId/name/index.yaml#/path',
  '#/components/parameters/ServerId':
   'JSON Pointer points to missing location: ./components/parameters/ServerId.yaml#/ServerId' }
```
