### ISSUE TITLE
Can't run as docker image

### ISSUE THREAD

**Issue by sigmaadam** [moon0326/swagger-ui-watcher#33]
Hi,

I'm running this project on my local mac and it's working,
when I'm wrapping it with docker file and run it inside docker, it throw an error:

swagger-ui-watcher ./src/resources/swagger.yml --port=9000

Listening on http://127.0.0.1:9000
(node:18) UnhandledPromiseRejectionWarning: Error: Exited with code 3
    at ChildProcess.cp.once.code (/swagger/node_modules/opn/index.js:84:13)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Socket.stream.socket.on (internal/child_process.js:336:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:561:12)
(node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by moon0326** [comment]
Sorry for the late response. Could you describe your issue in details please?

Are you running the command in a docker after SSHing into it? That will probably not work because this package tries to open a browser and your docker image might not have it.

If that's the case, I can add an option to not open a browser. Let me know.

**Comment by lud-hu** [comment]
I currently ran into the same problem as mentioned above.
I want to run swagger-ui-watcher in a virtual machine and open the ui in a browser in the host machine.

So would it be possible to add the option to not open a browser?

**Comment by moon0326** [comment]
Closing as no reply from the OP
