### ISSUE TITLE
Support adding withCredentials as a valid argument to support cookie based authentication from different origins?

### ISSUE THREAD

**Issue by louisnow** [moon0326/swagger-ui-watcher#37]
Maybe a --withCredentials=true option in the command line?
https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md#network
To make this more generic and support any kind of value that swagger UI itself supports, maybe we
can read data from package.json and pass it along? Or maybe a `--config=<CONFIG FILE>`
Nodemon does something [similar](https://github.com/remy/nodemon#packagejson).

**Comment by louisnow** [comment]
Never mind, I can see it [isn't supported](https://github.com/swagger-api/swagger-ui/issues/4805) by swagger-ui-dist

**Comment by louisnow** [comment]
Reopening due to #38

**Comment by moon0326** [comment]
Closing it as the PR has been merged and released.
