### ISSUE TITLE
Semantic error at security.0

### ISSUE THREAD

**Issue by b1f6c1c4** [moon0326/swagger-ui-watcher#4]
The following error is shown
```
Semantic error at security.0
Security requirements must match a security definition
```
for
```yaml
openapi: "3.0.0"
info:
  title: Sample
  version: 1.0.0
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []
paths:
  /:
    get:
      summary: Check system status
      operationId: checkStatus
      tags:
        - default
      responses:
        200:
          description: Healthy
          content:
            aplication/json:
              schema:
                type: object
```
But this is a valid yaml, verified by [https://editor.swagger.io](https://editor.swagger.io).

**Comment by pranav93** [comment]
I've used the same swaggerfile and is not showing any errors in browser.
[https://ibb.co/g7Sq4w](https://ibb.co/g7Sq4w)

**Comment by moon0326** [comment]
Sorry for the delay in response. I will look into it over the weekend.

**Comment by b1f6c1c4** [comment]
The error disappeared after `npm i -g swagger-ui-watcher` again. I can't reproduce the same error again, so please close this issue.
