### ISSUE TITLE
Fix security warnings by updating packages

### ISSUE THREAD

**Issue by louisnow** [moon0326/swagger-ui-watcher#41]
`commander` is on [v5](https://github.com/tj/commander.js)
`opn` is now called `open` and is on [v7](https://github.com/sindresorhus/open#readme)

Also fix security warnings
![2020-06-06-022937_509x44_scrot](https://user-images.githubusercontent.com/6024271/83924263-d8f92000-a7a1-11ea-8851-c967bf3fab66.png)

This can be a major version upgrade, as only the oldest active LTS versions of node and up are supported. Deprecated/EOL versions of node are not supported anymore.

**Comment by moon0326** [comment]
Thank you for the report. I will see what I can do.
