### ISSUE TITLE
Add option to build the bundled json without watching

### ISSUE THREAD

**Issue by pranav93** [moon0326/swagger-ui-watcher#5]
**Why is it needed?**
Currently the tool will build the bundle if and only if we have changed the file. The build option will allow user to create bundled file for swagger-ui deployment.

Proposed options:
For build
```
swagger-ui-watcher build swagFile targetFolder --host=host --port=port --bundle=bundle
```
For development
```
swagger-ui-watcher serve swagFile targetFolder --host=host --port=port --bundle=bundle
```
The serve part will be same as current command for watching

**Comment by moon0326** [comment]
@pranav93 Nice idea. I will implement it over the weekend. It should be pretty easy to implement. I think the build command would not need --host and --port options though.

**Comment by pranav93** [comment]
I've already done it on my fork, can I contribute? @moon0326

**Comment by moon0326** [comment]
Closing it as pranav93's PR has been merged and published.
