### ISSUE TITLE
Unwanted spec updates for every file present in directory on startup

### ISSUE THREAD

**Issue by louisnow** [moon0326/swagger-ui-watcher#51]
The 'all' parameter will call the callback for every file present in the folder being watched with an 'add' eventType. This is problematic as we only want it to run for 'change' eventTypes. If you have a lot of files in the directory you're watching, the callback fires for every file simply existing on startup instead of just on change.
![2020-06-06-185145_732x308_scrot](https://user-images.githubusercontent.com/6024271/83945248-22d81980-a827-11ea-87c2-743a8050e35b.png)

The fix is to simply change `.on('all'` to `.on('change'`

_Originally posted by @louisnow in https://github.com/moon0326/swagger-ui-watcher/pull/36#discussion_r436268966

**Comment by moon0326** [comment]
merged and released as 2.1.10. Thank you for the PR!
