### ISSUE TITLE
Security warning when installing swagger-ui-watcher

### ISSUE THREAD

**Issue by Pierre-Gilles** [moon0326/swagger-ui-watcher#56]
Hi!

First, thank you for this package. I use it every day to write my swagger docs, and it's really nice to work with 🙏

When installing this package, since yesterday I got a security warning flagged as "high" by NPM:

<img width="586" alt="Screenshot 2021-05-05 at 14 12 02" src="https://user-images.githubusercontent.com/7365207/117102948-f072cb80-adab-11eb-9477-c63874876261.png">

It comes from a security issue in a dependency, [xmlhttprequest-ssl](https://www.npmjs.com/package/xmlhttprequest-ssl) of [socket.io](https://www.npmjs.com/package/socket.io) used in this package.

I just checked, it seems this issue is not fixed in `socket.io` main repo as of now, so we might just have to wait until they release a fixed version of it :) 

To check if the issue is stil present in socket.io: 

```
git clone https://github.com/socketio/socket.io
cd socket.io
npm audit
```

I opened this issue to keep track of the issue. 

Thanks again for this module!

**Comment by sgerrand** [comment]
I've opened #57 to fix this specific issue. Any additional support you can provide to getting that change merged would be greatly appreciated!

**Comment by Pierre-Gilles** [comment]
Thanks for your PR.

Indeed, upgrading to socket.io 3.1.2 fixes the issue :) Let's hope it'll get merged !

**Comment by moon0326** [comment]
Thank you both @sgerrand  and @Pierre-Gilles for the taking time to open this issue.

I totally missed mentions and issue notifications. I've merged @sgerrand 's PR and the error should be gone now.
