### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by sgerrand** [moon0326/swagger-ui-watcher#59]
I opened #57 nearly a month ago to address a security related vulnerability but it hasn't been reviewed yet, which is concerning for me as a consumer of this npm package.

**Comment by moon0326** [comment]
Hi @sgerrand Sorry for the lack of communication. Somehow I never received notifications for the issues and PRs.

I will check on them now.

**Comment by moon0326** [comment]
I've published 2.1.12 with your PR https://www.npmjs.com/package/swagger-ui-watcher/v/2.1.12

**Comment by sgerrand** [comment]
Thank you!
