### ISSUE TITLE
Bump swagger-editor-dist to 5.x for OpenAPI 3.1

### ISSUE THREAD

**Issue by gbroques** [moon0326/swagger-ui-watcher#67]
Hi, I'd like to use this for previewing OpenAPI 3.1, as opposed to 3.0.

However, Swagger Editor 3.x is unable to render it. See below screenshot:

![image](https://github.com/moon0326/swagger-ui-watcher/assets/12969835/f414edea-25b7-4933-94b8-4f252a8e4821)

[According to this release post](https://github.com/swagger-api/swagger-editor/releases/tag/v4.10.0), Swagger Editor 5.x supports OpenAPI 3.1 for editing.

Is there any chance we can bump `swagger-editor-dist` to the latest alpha release such as [v5.0.0-alpha.75](https://github.com/swagger-api/swagger-editor/releases/tag/v5.0.0-alpha.75)?

**Comment by moon0326** [comment]
Hi @gbroques 

Thank you for opening the issue. It sounds like we can publish a beta version with Swagger Editor 5.0.0 alpha 75.

I'll look into it this week.

**Comment by gbroques** [comment]
> Hi @gbroques
> 
> Thank you for opening the issue. It sounds like we can publish a beta version with Swagger Editor 5.0.0 alpha 75.
> 
> I'll look into it this week.

Thanks @moon0326. I appreciate the quick response.

As an alternative, we could consider bumping to Swagger Editor [4.10.0](https://github.com/swagger-api/swagger-editor/compare/v4.9.2...v4.10.0) as it supports **rendering** OpenAPI 3.1, but *not* editing 3.1.

Swagger Editor 4 and 5 are available online:

* Swagger Editor 4 - https://editor.swagger.io/
* Swagger Editor 5 - https://editor-next.swagger.io/

**Comment by moon0326** [comment]
@gbroques, I've tested 4.10.x versions and they did not work :(

It seems like 4.10.x versions still don't support 3.1.0 for some reason. I'll play with it a bit more soon.

1. Download 4.10.x version (zip version is fine)
2. Open index.html
3. Change `openapi` version to 3.1.0

![Screenshot 2023-08-11 at 10 24 17 AM](https://github.com/moon0326/swagger-ui-watcher/assets/4723145/f870698f-0250-43f1-bec7-f9a0e6aeed5c)

**Comment by moon0326** [comment]
@gbroques So I tested all 4.10.x versions and none of them worked for OpenAPI 3.1.0 version.

I'll try to see if we can release a beta or alpha with v5.0 as I planned initially.

**Comment by gbroques** [comment]
> @gbroques So I tested all 4.10.x versions and none of them worked for OpenAPI 3.1.0 version.
> 
> I'll try to see if we can release a beta or alpha with v5.0 as I planned initially.

Thanks for looking into this @moon0326!!

**Comment by moon0326** [comment]
@gbroques I've released 2.1.2-beta.2 with Swagger 5.0.0-alpha-75

```
npm install swagger-ui-watcher@2.1.2-beta.2 -g
```

Please let me know if you encounter any errors. As I'm not familiar with OpenAPi 3.1.0 spec changes, I was not able to test much.

**Comment by gbroques** [comment]
> @gbroques I've released 2.1.2-beta.2 with Swagger Editor 5.0.0-alpha-75
> 
> ```
> npm install swagger-ui-watcher@2.1.2-beta.2 -g
> ```
> 
> Please let me if you encounter any errors. As I'm unfamiliar with OpenAPi 3.1.0 spec changes, I could not test much.

Thank you moon, I'll let you know if I encounter anything!

**Comment by lucasrabiec** [comment]
> @gbroques I've released 2.1.2-beta.2 with Swagger Editor 5.0.0-alpha-75
> 
> ```
> npm install swagger-ui-watcher@2.1.2-beta.2 -g
> ```
> 
> Please let me if you encounter any errors. As I'm unfamiliar with OpenAPi 3.1.0 spec changes, I could not test much.

Beta also works for me. Is there any chance of releasing it officially?
